# -*- coding: ascii -*-
"""
TLS handshake bump certificate template data.

This module is data-only so a generator script can update it without touching
runtime logic.
"""

from __future__ import absolute_import

# 256 chars raises the response payload MTU while keeping the template static.
CN_LEN = 256
CN_OFFSETS = (71, 380)

CERT_TEMPLATE_DER_B64 = (
    b'MIIFBzCCA++gAwIBAgIUOWH8Ju2RPDYUpw+pJ9lrbkqR94YwDQYJKoZIhvcNAQELBQAwggERMYIB'
    b'DTCCAQkGA1UEAwyCAQBhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh'
    b'YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh'
    b'YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh'
    b'YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh'
    b'YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhMB4XDTI2MDEwNDIxNDYx'
    b'MFoXDTI2MDEwNTIxNDYxMFowggERMYIBDTCCAQkGA1UEAwyCAQBhYWFhYWFhYWFhYWFhYWFhYWFh'
    b'YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh'
    b'YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh'
    b'YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh'
    b'YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFh'
    b'YWFhYWFhYWFhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4dnc0lZi9Ff6Wuy6X2yn'
    b'8E1oMfdj2MnraRnRmbaTqynt8Y12TTO4zGWujtTBJR4meGVz8yVY1bC5Rr3o8teQ8GAOwXhQgJWN'
    b'33KFg0h8IK1YR+cG1zxFTSlGpTxpP+ILXysV2fWFsoaQ7QVvlesw8htBzAjqQWRA/dQyQopN3/rZ'
    b'zwVlEfCQRbOAswsxNSmULfsPZzatN+k/Wj0PZ8pxcIlxptn8Yxevu4/nPn4AcI/+cxD+Nsnkm8ll'
    b'G/hec7b5e+5Zo/42MgscZIrO7ErpazuQmb5UwoIa6523SvTEaI6/3sW5pgFKlYBNaU7589JAV089'
    b'QAIGgarTuJLUbgTF5QIDAQABo1MwUTAdBgNVHQ4EFgQUlWCcEVqZ3h0gjcOXIFk7cKXDc9wwHwYD'
    b'VR0jBBgwFoAUlWCcEVqZ3h0gjcOXIFk7cKXDc9wwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0B'
    b'AQsFAAOCAQEAgJyZGwPZoRCzM4Q/pMEjz7PS6cJIIkQKzvPp1Muf0SWOhGzIW5O56WWiqCGPysQU'
    b'OSUOTROzSwsamABxeH+/SFo0oOB8SvFmnHpu2NxI/gloMLgc02P7xPxVt3OEhH+SM7+n+epYr9hM'
    b'SjuehmKyz6D989mdpw4FcqhWnhzcpRY+aNylG3ajSLcU04MS2jiKaC/cWekTurgGR6eO6aap4ygt'
    b'QYUBYKSpAVB+FkkTRNzGF3g6SJTAVB1g8UIVyD/XHESdxluWgLe4lOaa/bw0eXyola96Mdp2ArPz'
    b'ErHzVg7bfszr+O1eqg5FDAMJUtwP62F0vGH0FXjNpKJiVVRriA=='
)
