# -*- coding: ascii -*-
"""
Named logging profiles for troubleshooting sessions.
"""

from __future__ import absolute_import


LOG_PROFILES = {
    # SCP stall debugging over ICMP + SOCKS.
    'scp_stalled_icmp_socks': {
        'log_component_transport_icmp': True,
        'log_component_tunnel': True,
        'log_component_channel': True,
        'log_component_module_socks': True,
        'log_event_whitelist': (
            'cli.*',
            'sock.connect*',
            'sock.server_*',
            'sock.relay_*',
            'sock.pump_*',
            'sock.pump_stats',
            'channel.open*',
            'channel.close*',
            'channel.send_buf_*',
            'channel.drain',
            'tunnel.send_blocked',
            'tunnel.send_window_*',
            'tunnel.retransmit*',
            'tunnel.ack_detail',
            'tunnel.reliability_state',
            'tunnel.keepalive_*',
            'tunnel.packet_decode_failed',
            'tunnel.state',
            'tunnel.window_*',
            'tunnel.mtu_*',
            'tunnel.timeout_*',
            'tunnel.connected',
            'tunnel.closed',
            'icmp.*',
        ),
        'log_event_blacklist': (),
    },
    # Focused ICMP retransmit troubleshooting (default during debug).
    'icmp_retransmit_debug': {
        'log_component_transport_icmp': True,
        'log_component_tunnel': True,
        'log_component_channel': True,
        'log_event_whitelist': (
            'cli.*',
            'tunnel.packet_*',
            'tunnel.packet_decode_failed',
            'tunnel.ack',
            'tunnel.ack_detail',
            'tunnel.retransmit*',
            'tunnel.send_blocked',
            'tunnel.send_window_distance',
            'tunnel.send_window_full',
            'tunnel.send_window_inconsistent',
            'tunnel.recv_window',
            'tunnel.deliver_segments',
            'tunnel.reliability_state',
            'tunnel.keepalive_*',
            'tunnel.state',
            'tunnel.window_*',
            'tunnel.mtu_*',
            'tunnel.timeout_*',
            'tunnel.handshake_*',
            'tunnel.ack_send_failed',
            'tunnel.serve_error',
            'tunnel.connected',
            'tunnel.closed',
            'tunnel.response_cap',
            'tunnel.pacer_target',
            'tunnel.request_state_unexpected',
            'tunnel.tick_error',
            'tunnel.bg_error',
            'icmp.*',
            'channel.open*',
            'channel.close*',
            'channel.send_buf_*',
            'channel.pack',
            'channel.drain',
            'sock.connect*',
            'sock.server_*',
            'sock.relay_*',
        ),
        'log_event_blacklist': (),
    },
    # Heavy tunnel reliability instrumentation (all tunnel events).
    'tunnel_reliability_verbose': {
        'log_component_transport_icmp': True,
        'log_component_transport_dns': True,
        'log_component_transport_tls': True,
        'log_component_tunnel': True,
        'log_component_channel': True,
        'log_event_whitelist': (
            'cli.*',
            'tunnel.*',
            'channel.*',
            'icmp.*',
            'dns.*',
            'tls.*',
        ),
        'log_event_blacklist': (),
    },
    # Channel close debugging with targeted transport/tunnel context.
    'channel_close_debug': {
        'log_component_transport_icmp': True,
        'log_component_transport_dns': True,
        'log_component_tunnel': True,
        'log_component_channel': True,
        'log_component_module_socks': True,
        'log_event_whitelist': (
            'cli.*',
            'channel.*',
            'sock.*',
            'tunnel.state',
            'tunnel.connected',
            'tunnel.closed',
            'tunnel.packet_decode_failed',
            'tunnel.mtu_*',
            'tunnel.window_*',
            'tunnel.timeout_*',
            'tunnel.retransmit*',
            'tunnel.send_blocked',
            'tunnel.send_window_*',
            'tunnel.request_state_unexpected',
            'tunnel.ack_send_failed',
            'tunnel.serve_error',
            'tunnel.responder_error',
            'tunnel.tick_error',
            'tunnel.bg_error',
            'icmp.*',
            'dns.*',
        ),
        'log_event_blacklist': (
            'channel.pack',
            'channel.drain',
            'sock.pump_stats',
            'icmp.send',
            'icmp.recv',
            'dns.send',
            'dns.recv',
        ),
    },
    # Enable ICMP transport logs (keeps default event blacklist).
    'icmp_transport': {
        'log_component_transport_icmp': True,
    },
    # Enable DNS transport logs (keeps default event blacklist).
    'dns_transport': {
        'log_component_transport_dns': True,
    },
    # Enable TLS transport logs (keeps default event blacklist).
    'tls_transport': {
        'log_component_transport_tls': True,
    },
    # DNS troubleshooting with tunnel, channel, and SOCKS context.
    'dns_troubleshoot': {
        'log_component_transport_dns': True,
        'log_component_tunnel': True,
        'log_component_channel': True,
        'log_component_module_socks': True,
        'log_event_whitelist': (
            'cli.*',
            'dns.*',
            'tunnel.handshake_*',
            'tunnel.state',
            'tunnel.connected',
            'tunnel.closed',
            'tunnel.mtu_*',
            'tunnel.window_*',
            'tunnel.timeout_*',
            'tunnel.wait',
            'tunnel.ack',
            'tunnel.ack_detail',
            'tunnel.pacer_state',
            'tunnel.retransmit*',
            'tunnel.send_blocked',
            'tunnel.recv_window',
            'tunnel.packet_*',
            'tunnel.packet_decode_failed',
            'tunnel.reliability_state',
            'tunnel.keepalive_*',
            'tunnel.request_state_unexpected',
            'tunnel.response_cap',
            'tunnel.send_window_*',
            'tunnel.serve_error',
            'tunnel.responder_error',
            'channel.open*',
            'channel.close*',
            'channel.half_close*',
            'channel.send_buf_*',
            'channel.drain',
            'channel.pack',
            'channel.write_wait',
            'sock.connect*',
            'sock.server_*',
            'sock.relay_*',
            'sock.pump_*',
            'sock.pump_stats',
        ),
        'log_event_blacklist': (),
    },
    # DNS + SOCKS session stall debugging (SSH/SCP over DNS transport).
    'dns_socks_stall_debug': {
        'log_component_transport_dns': True,
        'log_component_transport_icmp': True,
        'log_component_tunnel': True,
        'log_component_channel': True,
        'log_component_module_socks': True,
        'log_event_whitelist': (
            'cli.*',
            'dns.*',
            'icmp.*',
            'tunnel.state',
            'tunnel.connected',
            'tunnel.closed',
            'tunnel.timeout_*',
            'tunnel.retransmit*',
            'tunnel.send_blocked',
            'tunnel.send_window_*',
            'tunnel.window_*',
            'tunnel.mtu_*',
            'tunnel.ack',
            'tunnel.ack_detail',
            'tunnel.recv_window',
            'tunnel.packet_*',
            'tunnel.packet_decode_failed',
            'tunnel.request_state_unexpected',
            'tunnel.response_cap',
            'tunnel.reliability_state',
            'tunnel.keepalive_*',
            'tunnel.pacer_state',
            'tunnel.pacer_target',
            'tunnel.ack_send_failed',
            'tunnel.serve_error',
            'tunnel.responder_error',
            'tunnel.tick_error',
            'tunnel.bg_error',
            'channel.open*',
            'channel.close*',
            'channel.send_buf_*',
            'channel.drain',
            'channel.pack',
            'channel.write_wait',
            'sock.connect*',
            'sock.server_*',
            'sock.relay_*',
            'sock.pump_*',
            'sock.pump_start',
            'sock.pump_stop',
            'sock.pump_stats',
        ),
        'log_event_blacklist': (
            'dns.cname_followup',
        ),
    },
    # File transfer put timeouts with fast polling.
    'file_transfer_put_debug': {
        'log_component_transport_dns': True,
        'log_component_transport_icmp': True,
        'log_component_tunnel': True,
        'log_component_channel': True,
        'log_component_module_file_transfer': True,
        'log_event_whitelist': (
            'cli.*',
            'file.*',
            'module.*',
            'channel.open*',
            'channel.close*',
            'channel.half_close*',
            'channel.send_buf_*',
            'channel.write_wait',
            'channel.drain',
            'channel.pack',
            'tunnel.state',
            'tunnel.connected',
            'tunnel.closed',
            'tunnel.timeout_*',
            'tunnel.handshake_*',
            'tunnel.mtu_*',
            'tunnel.window_*',
            'tunnel.send_blocked',
            'tunnel.send_window_*',
            'tunnel.retransmit*',
            'tunnel.packet_*',
            'tunnel.packet_decode_failed',
            'tunnel.ack',
            'tunnel.ack_detail',
            'tunnel.recv_window',
            'tunnel.response_cap',
            'tunnel.request_state_unexpected',
            'tunnel.pacer_state',
            'tunnel.reliability_state',
            'tunnel.keepalive_*',
            'tunnel.pacer_target',
            'tunnel.ack_send_failed',
            'tunnel.tick_error',
            'tunnel.bg_error',
            'tunnel.serve_error',
            'tunnel.responder_error',
            'icmp.*',
            'dns.*',
        ),
        'log_event_blacklist': (),
    },
    # SOCKS channel starvation debugging (focused on fairness signals).
    'socks_starvation': {
        'log_component_tunnel': True,
        'log_component_channel': True,
        'log_component_module_socks': True,
        'log_event_whitelist': (
            'cli.*',
            'sock.connect*',
            'sock.server_*',
            'sock.relay_*',
            'channel.open*',
            'channel.close*',
            'channel.drain',
            'tunnel.send_blocked',
            'tunnel.send_window_distance',
            'tunnel.send_window_full',
            'tunnel.send_window_inconsistent',
            'tunnel.retransmit*',
            'tunnel.state',
            'tunnel.window_*',
        ),
        'log_event_blacklist': (
            'tunnel.packet_*',
            'channel.pack',
            'channel.send_buf_*',
            'sock.pump_stats',
        ),
    },
    # Broad tunnel debugging (turns on protocol/channel and clears blacklist).
    'tunnel_verbose': {
        'log_component_tunnel': True,
        'log_component_channel': True,
        'log_component_protocol': True,
        'log_event_blacklist': (),
    },
    # Log everything from all components without event filtering.
    'all_events': {
        'log_component_transport_dns': True,
        'log_component_transport_icmp': True,
        'log_component_transport_tls': True,
        'log_component_tunnel': True,
        'log_component_channel': True,
        'log_component_protocol': True,
        'log_component_module_socks': True,
        'log_component_module_file_transfer': True,
        'log_event_whitelist': (),
        'log_event_blacklist': (),
    },
    # Focused SOCKS+ICMP throughput debugging.
    'socks_throughput_debug': {
        'log_component_transport_icmp': True,
        'log_component_tunnel': True,
        'log_component_module_socks': True,
        'tunnel_pacer_summary_interval': 1.0,
        'log_event_whitelist': (
            'sock.pump_stats',
            'sock.pump_*',
            'sock.relay_*',
            'channel.send_buf_*',
            'channel.drain',
            'channel.write_wait',
            'icmp.send',
            'icmp.recv',
            'icmp.send_blocked',
            'tunnel.window_*',
            'tunnel.send_blocked',
            'tunnel.pacer_adjust',
            'tunnel.pacer_summary',
            'tunnel.packet_*',
        ),
        'log_event_blacklist': (),
    },
    # Broad SOCKS instrumentation (relay, pumps, and channel lifecycle).
    'socks_instrumentation': {
        'log_component_tunnel': True,
        'log_component_channel': True,
        'log_component_module_socks': True,
        'log_event_whitelist': (
            'cli.*',
            'sock.*',
            'channel.*',
            'tunnel.state',
            'tunnel.connected',
            'tunnel.closed',
            'tunnel.mtu_*',
            'tunnel.window_*',
        ),
        'log_event_blacklist': (),
    },
    # Disable all component logging (errors still pass).
    'no_logging': {
        'log_component_transport_dns': False,
        'log_component_transport_icmp': False,
        'log_component_tunnel': False,
        'log_component_channel': False,
        'log_component_protocol': False,
        'log_component_module_socks': False,
        'log_component_module_file_transfer': False,
        'log_event_whitelist': (),
        'log_event_blacklist': ('*',),
    },
    # Adaptive pacing state tracing (minimal noise).
    'tunnel_pacing': {
        'log_component_tunnel': True,
        'tunnel_pacer_summary_interval': 1.0,
        'log_event_whitelist': (
            'cli.*',
            'tunnel.state',
            'tunnel.wait',
            'tunnel.handshake_*',
            'tunnel.ack_send_failed',
            'tunnel.mtu_*',
            'tunnel.window_*',
            'tunnel.timeout_*',
            'tunnel.connected',
            'tunnel.closed',
            'tunnel.pacer_adjust',
            'tunnel.pacer_state',
            'tunnel.pacer_summary',
        ),
        'log_event_blacklist': (),
    },
}


def apply_log_profile(config, name, overrides=None):
    """
    Apply a named logging profile to a Config instance.

    Args:
        config: Config instance to update.
        name: Profile name (must exist in LOG_PROFILES).
        overrides: Optional dict of per-key overrides.

    Returns:
        dict of applied settings.
    """
    if not name:
        return None
    profile = LOG_PROFILES.get(name)
    if profile is None:
        raise ValueError('Unknown log profile: %s' % name)
    settings = {}
    settings.update(profile)
    if overrides:
        settings.update(overrides)
    for key, value in settings.items():
        if not hasattr(config, key):
            raise ValueError('Unknown log config key in profile: %s' % key)
        setattr(config, key, value)
    return settings
